name: Build APK

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Build and assemble a debug APK file
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Upload Discord apk as artifact
        uses: actions/upload-artifact@v2
        with:
          name: blast
          path: app/build/outputs/apk/debug/app-debug.apk
